name: Build, test & deploy app
env:
  WORKING_DIR_FE: ./frontend
  WORKING_DIR_INFRA: ./infrastructure
on:
  push:
  workflow_dispatch:

jobs:
  install:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIR_FE }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 10

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: node_modules-

      - name: Install dependencies
        run: |
          npm ci

  build:
    needs: install
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIR_FE }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 10

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: node_modules-${{ hashFiles('**/package-lock.json') }}

      - name: Build
        run: |
          npm rebuild node-sass --force
          npm run build --colors

      - name: Cache Node modules and build folder
        if: ${{ github.ref == 'refs/heads/master' }}
        uses: actions/cache@v3
        with:
          path: |
            ~/.npm
            ${{ env.WORKING_DIR_FE }}/node_modules
            ${{ env.WORKING_DIR_FE }}/build
          key: ${{ runner.os }}-build-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-build-${{ github.run_id }}

  test:
    needs: install
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ env.WORKING_DIR_FE }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 10

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: "**/node_modules"
          key: node_modules-${{ hashFiles('**/package-lock.json') }}

      - name: Run tests
        run: |
          npm run test

  deploy:
#    needs: [ build, test ]
#    if: ${{ github.ref == 'refs/heads/master' }}
#    needs: [ build ]
    if: ${{ github.ref == 'refs/heads/testing' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install ansible
        run: pip3 install ansible boto boto3

      - name: Deploy via Ansible
        uses: dawidd6/action-ansible-playbook@v2
        with:
          playbook: ec2_deploy.yml
          directory: "${{ env.WORKING_DIR_INFRA }}/ansible"
          requirements: requirements.yml
          key: ${{secrets.SSH_PRIVATE_KEY}}
          vault_password: ${{secrets.VAULT_PASSWORD}}
          options: |
            --user ec2-user
            --verbose